export const LOVES_PART_1 = [
  "Handwritten notes or cards, slipped into her lunch, car, or purse",
  "Remembering small things she mentioned in passing",
  "Planning a date night without her having to ask",
  "Complimenting her appearance genuinely",
  "Holding hands in public",
  "Doing a chore she normally handles, unprompted",
  "Sending a sweet text in the middle of the day",
  "Bringing home her favorite snack or treat",
  "Putting your phone away when she's talking",
  "Giving her a massage without expecting anything",
  "Asking about her day and really listening",
  "Flowers for no reason",
  "Remembering and honoring her preferences",
  "Planning something around her interests, not yours",
  "Cooking her favorite meal",
  "Checking in when she's stressed",
  "Celebrating her wins enthusiastically",
  "Apologizing sincerely when you've been wrong",
  "Noticing when she's off and asking gently",
  "Leaving her a loving voicemail",
  "Dressing up for her",
  "Making plans with her family or friends",
  "Telling others good things about her",
  "Asking her opinion on something important and genuinely considering it",
  "Remembering how she takes her coffee and having it ready",
];

export const LOVES_PART_2 = [
  "Watching a show she loves even if it's not your thing",
  "Texting her when you're thinking of her, for no reason",
  "Making her feel safe enough to say anything",
  "Planning a trip based entirely on what she'd love",
  "Supporting her friendships and encouraging her to go out",
  "Being the one who remembers the reservation, directions, or details",
  "Telling her she's beautiful when she doesn't feel it",
  "Making her feel chosen, not just settled for",
  "Alleviating the \"mental load\" by being the default person for something",
  "Being the calm one when she's spiraling",
  "Lighting candles or setting the mood without being asked",
  "Reaching for her hand first",
  "Protecting her sleep — keeping noise down, handling the kids",
  "Cleaning the house or car",
  "Leaving the last of something for her",
  "Saying \"that was my fault\" quickly and without defensiveness",
  "Sending flowers to her workplace so her colleagues see",
  "Making her feel like the most interesting person in the room",
  "Knowing when to be funny and when to just be present",
  "Saving something she'd like — an article, a recipe, a meme — and sharing it",
  "Remembering the names of her friends and asking about them by name",
  "Thanking her specifically for things she does, not just generically",
  "Making her feel like being with her is the best part of your day",
  "Making her laugh",
  "Telling her you're proud of her",
];

export const GOALS = [
  "More connection",
  "Better timing",
  "Less conflict",
  "More romance",
  "Deeper intimacy",
  "Be more present",
  "Reduce misunderstandings",
  "Surprise her more often",
];
