/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLovesImageRouteImport } from './routes/api/loves/image'
import { Route as ApiV1FeedbackOtherRouteImport } from './routes/api/v1/feedback/other'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLovesImageRoute = ApiLovesImageRouteImport.update({
  id: '/api/loves/image',
  path: '/api/loves/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FeedbackOtherRoute = ApiV1FeedbackOtherRouteImport.update({
  id: '/api/v1/feedback/other',
  path: '/api/v1/feedback/other',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/loves/image': typeof ApiLovesImageRoute
  '/api/v1/feedback/other': typeof ApiV1FeedbackOtherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/loves/image': typeof ApiLovesImageRoute
  '/api/v1/feedback/other': typeof ApiV1FeedbackOtherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/api/loves/image': typeof ApiLovesImageRoute
  '/api/v1/feedback/other': typeof ApiV1FeedbackOtherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboarding' | '/api/loves/image' | '/api/v1/feedback/other'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding' | '/api/loves/image' | '/api/v1/feedback/other'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/api/loves/image'
    | '/api/v1/feedback/other'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiLovesImageRoute: typeof ApiLovesImageRoute
  ApiV1FeedbackOtherRoute: typeof ApiV1FeedbackOtherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/loves/image': {
      id: '/api/loves/image'
      path: '/api/loves/image'
      fullPath: '/api/loves/image'
      preLoaderRoute: typeof ApiLovesImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/feedback/other': {
      id: '/api/v1/feedback/other'
      path: '/api/v1/feedback/other'
      fullPath: '/api/v1/feedback/other'
      preLoaderRoute: typeof ApiV1FeedbackOtherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  ApiLovesImageRoute: ApiLovesImageRoute,
  ApiV1FeedbackOtherRoute: ApiV1FeedbackOtherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
